const contentWrapperEl = document.getElementById("contentWrapper");
const questionBtnEl = document.getElementById("questionBtn");
const answerBtnBtnEl = document.getElementById("answerBtn");
const questionTextEl = document.getElementById("questionText");
const answerTextEl = document.getElementById("answerText");
const startBtnEl = docunment.getElementById("startBtn");

function startQuiz(){
    contentWrapperEl.style.display = "flex";
    const startBtn2 = document.getElementById("startBtn").style.display = "none";
}



function showQuestion(){
    const quesBank = [
     // Basics
  ["Why is compliance with weight and balance limits critical?", "Because exceeding maximum weight compromises structural integrity, and CG outside limits results in control difficulty."],
  ["What is the only force that counteracts weight in flight?", "Lift."],
  ["What factors affect the lift generated by an airfoil?", "Airfoil design, angle of attack (AOA), airspeed, and air density."],
  
  // Effects of Weight
  ["List five performance deficiencies caused by an overloaded aircraft.", "Higher takeoff speed, longer takeoff run, reduced rate/angle of climb, lower maximum altitude, shorter range, reduced cruising speed, reduced maneuverability, higher stall speed, higher approach/landing speed, longer landing roll."],
  ["What is usually the first indication of poor performance due to overloading?", "Difficulty during takeoff."],
  ["How much does aviation gasoline (AVGAS) weigh?", "6 pounds per gallon."],
  ["Why must fuel weight be considered in preflight planning?", "Because reducing fuel lowers airplane weight but decreases range."],

  // Balance and Center of Gravity
  ["What is balance in an aircraft?", "The location of the center of gravity (CG), important for stability and safety."],
  ["What condition results from a CG too far forward?", "Nose-heavy condition, causing difficulty raising the nose."],
  ["What condition results from a CG too far aft?", "Tail-heavy condition, reducing stability and making stall/spin recovery harder."],
  ["How can lateral unbalance occur?", "By uneven fuel tank usage or uneven weight distribution on left/right sides."],
  ["Why is excessive trim undesirable?", "It reduces aerodynamic efficiency and primary control travel distance."],

  // Stability
  ["What problems arise from a nose-heavy loading condition?", "Difficulty raising the nose during takeoff/landing, higher stall speeds, higher landing speeds, excessive nosewheel loads."],
  ["What problems arise from a tail-heavy loading condition?", "Reduced longitudinal stability, light control forces, easy overstressing, poor stall/spin recovery."],
  ["What is the aft CG limit?", "The most rearward CG position for which safe maneuvering is possible."],
  ["What happens as CG moves aft?", "Stability decreases, control difficulty increases, stall/spin recovery worsens."],

  // Management of Weight & Balance
  ["Where are official CG limits published?", "Type Certificate Data Sheet (TCDS), aircraft specifications, and AFM/POH."],
  ["Who controls variable factors that affect CG?", "The pilot, through loading and fuel management."],
  ["What regulation requires pilots to comply with AFM operating limits, including weight and balance?", "14 CFR 91.9."],
  ["How often must aircraft with 20+ seats or >6,000 lbs payload be weighed?", "Every 36 calendar months (14 CFR 125)."],
  ["What Advisory Circular provides negligible weight change criteria?", "AC 43.13-1."],
  ["What is considered negligible weight change for aircraft under 5,000 lbs?", "1 pound or less."],
  ["What is considered negligible CG change for fixed-wing aircraft?", "Any change less than 0.05% of Mean Aerodynamic Chord (MAC)."],

  // Definitions
  ["Define Arm (moment arm).", "The horizontal distance from the reference datum to the CG of an item."],
  ["Define Basic Empty Weight.", "The standard empty weight plus optional and special equipment installed."],
  ["Define CG Range.", "The distance between the forward and aft CG limits."],
  ["Define Datum.", "An imaginary vertical plane or line from which all arms are measured."],
  ["Define Moment.", "Weight multiplied by arm, expressed in inch-pounds."],
  ["What is a Moment Index?", "A moment divided by a constant to simplify calculations."],
  ["What is Useful Load?", "The weight of pilot, passengers, baggage, usable fuel, and drainable oil."],
  ["What is Payload?", "The weight of occupants, baggage, and cargo (not including fuel)."],
  ["What is Maximum Ramp Weight?", "The total loaded weight including taxi and run-up fuel."],
  ["What is Maximum Takeoff Weight?", "The maximum allowable weight for takeoff."],
  ["What is Zero Fuel Weight?", "The maximum weight of an aircraft without usable fuel."],

  // Computations
  ["What formula determines CG?", "CG = Total Moment ÷ Total Weight."],
  ["How is a new CG calculated after shifting weight?", "By adjusting the total moment and dividing by total weight."],
  ["What happens to total moments when weight is moved aft?", "They increase."],
  ["What happens to total moments when weight is moved forward?", "They decrease."],
  ["Why are fuel tanks often located near the CG in small aircraft?", "So fuel burn has little effect on CG."],

  // Restrictions & Operations
  ["Why may an aircraft not be able to take off at max gross weight?", "Because density altitude, runway length, slope, wind, and obstacles may require a weight reduction."],
  ["Why do some small aircraft make it difficult to exceed CG limits?", "Because seats, baggage, and fuel are located near the CG."],
  ["Why might an aircraft be out of CG limits even if within useful load?", "Because of improper distribution of weight."],
];
    const bankLength = quesBank.length;

    let randomQAnum = Math.floor(Math.random() * bankLength);
    
    let randomQandA = quesBank[randomQAnum];

    let currentQues = randomQandA[0];

    globalThis.currentAns = randomQandA[1];

    questionTextEl.innerText = currentQues;

    answerTextEl.innerText = "";

    questionBtnEl.style.display = "none";

    answerBtnBtnEl.style.display = "block";
    // console.log(currentQues);
    // console.log(currentAns);
}

function showAnswer(){
    const answerTextEl = document.getElementById("answerText");
    answerTextEl.innerText = currentAns;
    questionBtnEl.style.display = "block";
    answerBtnBtnEl.style.display = "none";
}






