const contentWrapperEl = document.getElementById("contentWrapper");
const questionBtnEl = document.getElementById("questionBtn");
const answerBtnBtnEl = document.getElementById("answerBtn");
const questionTextEl = document.getElementById("questionText");
const answerTextEl = document.getElementById("answerText");
const startBtnEl = docunment.getElementById("startBtn");

function startQuiz(){
    contentWrapperEl.style.display = "flex";
    const startBtn2 = document.getElementById("startBtn").style.display = "none";
}



function showQuestion(){
    const quesBank = [
      // FAA Weather Services
  ["What FAA publication provides details about aviation weather services?", "The FAA’s Aviation Weather Services (AC 00-45)."],
  ["What is the primary purpose of aviation weather services?", "To enhance safety and efficiency of flight operations by providing timely, accurate weather information."],
  ["What are the two categories of aviation weather products?", "Observations and forecasts."],

  // Observations
  ["What does METAR stand for?", "Meteorological Aerodrome Report."],
  ["How often are METARs issued?", "Every hour, routinely, with special reports (SPECI) issued as needed."],
  ["What does 'AUTO' mean in a METAR?", "Report generated by an automated weather station without human intervention."],
  ["What is a SPECI?", "A special weather report issued when significant changes occur between routine METARs."],
  ["What does the 'RMK' section of a METAR contain?", "Remarks with additional information such as weather phenomena or station-specific details."],
  ["What does PIREP stand for?", "Pilot Weather Report."],
  ["What information does a PIREP provide?", "In-flight weather observed by pilots, including turbulence, icing, visibility, and cloud tops."],
  ["What are the two types of PIREPs?", "Routine (UA) and Urgent (UUA)."],

  // Forecasts
  ["What does TAF stand for?", "Terminal Aerodrome Forecast."],
  ["How often are TAFs issued?", "Four times daily, valid for 24 or 30 hours depending on the airport."],
  ["What does 'BECMG' mean in a TAF?", "Gradual change in weather conditions over a specified time."],
  ["What does 'TEMPO' mean in a TAF?", "Temporary weather conditions lasting less than one hour at a time, and no more than half the forecast period."],
  ["What does 'PROB30' in a TAF mean?", "30% probability of thunderstorms or precipitation events."],
  ["What are Area Forecasts (FAs) being replaced by?", "Graphical Forecasts for Aviation (GFA)."],

  // Graphical Products
  ["What information does the GFA provide?", "Graphical depictions of weather elements like clouds, visibility, precipitation, icing, and turbulence."],
  ["How often is the GFA updated?", "Every 15 minutes with forecasts up to 18 hours."],
  ["What are SIGMETs issued for?", "Severe weather such as severe icing, turbulence, dust storms, sandstorms, or volcanic ash that affects all aircraft."],
  ["What are Convective SIGMETs issued for?", "Thunderstorms, tornadoes, hail ¾ inch or greater, and winds 50 knots or more."],
  ["How often are Convective SIGMETs issued?", "Hourly, with updates as needed."],
  ["What are AIRMETs issued for?", "Weather hazards that are less severe but may affect light aircraft, such as moderate icing, moderate turbulence, IFR, and mountain obscuration."],
  ["What are the three types of AIRMETs?", "Sierra (IFR/mountain obscuration), Tango (turbulence/strong winds), Zulu (icing/freezing levels)."],

  // Charts
  ["What does a Surface Analysis Chart show?", "Locations of highs, lows, fronts, and pressure systems based on observations."],
  ["How often are Surface Analysis Charts issued?", "Every 3 hours."],
  ["What does a Weather Depiction Chart show?", "Flight categories (VFR, MVFR, IFR, LIFR) based on cloud ceilings and visibility."],
  ["How often is the Weather Depiction Chart updated?", "Every 3 hours."],
  ["What does a Radar Summary Chart depict?", "Areas of precipitation, intensity, movement, and echoes."],
  ["What does a Significant Weather Prognostic Chart provide?", "Forecasts of significant weather hazards such as turbulence, icing, and IFR areas."],
  ["How often are Prognostic Charts issued?", "Four times daily."],
  ["What is a Convective Outlook Chart?", "A forecast of thunderstorm potential issued by the Storm Prediction Center (SPC)."],

  // Pilot Weather Resources
  ["What is Flight Service Station (FSS)?", "An FAA facility that provides pilots with preflight briefings, in-flight weather information, and other services."],
  ["What are the three types of FAA weather briefings available from FSS?", "Standard, Outlook, and Abbreviated."],
  ["What is included in a Standard Briefing?", "Complete weather information for a planned flight, including adverse conditions, forecasts, NOTAMs, and TFRs."],
  ["When would a pilot request an Outlook Briefing?", "For flights 6 hours or more in the future."],
  ["When would a pilot request an Abbreviated Briefing?", "When needing an update or supplement to a previous briefing."],
  ["What online system provides official FAA weather and flight planning services?", "Leidos Flight Service (1800wxbrief.com)."],
  ["What is DUATS and what replaced it?", "Direct User Access Terminal System, replaced by Leidos Flight Service."],

  // Advanced Applications
  ["Why are PIREPs critical for weather services?", "They provide real-time, in-flight weather conditions not captured by ground instruments."],
  ["Why are AIRMETs and SIGMETs important for pilots?", "They provide warnings about widespread hazardous conditions that may affect flight safety."],
  ["How do graphical products improve situational awareness?", "They allow pilots to visualize hazards such as turbulence and icing rather than only reading text reports."],
  ["What does the Aviation Weather Center (AWC) provide?", "Centralized access to weather charts, forecasts, and advisories for pilots."],
  ["What tool has replaced many textual forecasts with graphical depictions?", "The Graphical Forecasts for Aviation (GFA)."],
  ["What information can be accessed via ATIS?", "Automated airport broadcast with current weather, active runways, NOTAMs, and other information."],
  ["What is the difference between AWOS and ASOS?", "AWOS provides continuous weather observations; ASOS provides more comprehensive, automated observations with updates every minute."],
  ["Why are weather services especially important for VFR pilots?", "Because visibility, ceiling, turbulence, and icing hazards can directly impact their ability to maintain visual reference to the ground."],
];
    const bankLength = quesBank.length;

    let randomQAnum = Math.floor(Math.random() * bankLength);
    
    let randomQandA = quesBank[randomQAnum];

    let currentQues = randomQandA[0];

    globalThis.currentAns = randomQandA[1];

    questionTextEl.innerText = currentQues;

    answerTextEl.innerText = "";

    questionBtnEl.style.display = "none";

    answerBtnBtnEl.style.display = "block";
    // console.log(currentQues);
    // console.log(currentAns);
}

function showAnswer(){
    const answerTextEl = document.getElementById("answerText");
    answerTextEl.innerText = currentAns;
    questionBtnEl.style.display = "block";
    answerBtnBtnEl.style.display = "none";
}






